# Generated by Django 5.0.1 on 2024-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFolder', '0002_user_educationlevel_user_gender_user_imagepath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
